# Generated by Django 5.0.1 on 2024-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.CharField(max_length=10)),
                ('taskName', models.CharField(max_length=30)),
                ('processName', models.CharField(max_length=50)),
                ('queueName', models.CharField(max_length=50)),
                ('machineName', models.CharField(max_length=15)),
                ('jobKey', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('exceptionType', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('createDtime', models.CharField(max_length=50)),
                ('endDtime', models.CharField(max_length=50)),
                ('exceutionTime', models.CharField(max_length=50)),
            ],
        ),
    ]
