# Generated by Django 5.0.1 on 2024-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_queueitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitems',
            name='createDtime',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queueitems',
            name='endDtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queueitems',
            name='exceutionTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
