# Generated by Django 5.0.1 on 2024-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_queueitems_createdtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitems',
            name='startDtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='queueitems',
            name='createDtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queueitems',
            name='endDtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='queueitems',
            name='exceutionTime',
            field=models.TimeField(null=True),
        ),
    ]
